version: '3.8'

services:
  db:
    image: postgres:16
    container_name: django_blog_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: django_blog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: django_blog_pass123
    ports:
      - "5434:5432"
    volumes:
      - django_blog_pgdata:/var/lib/postgresql/data

volumes:
  django_blog_pgdata:
